# fly.toml app configuration file generated for lov on 2023-08-19T12:31:06-07:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "lov"
primary_region = "lax"
swap_size_mb = 512

[build]

[http_service]
  internal_port = 3001
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]

[mounts]
  source = "litefs"
  destination = "/db"

[env]
  DATABASE_URL = "file:/db/lov.db"
  SUPERTOKENS_WEBSITE_DOMAIN = "https://uptownhr.com"
  SUPERTOKENS_API_DOMAIN="https://lov.fly.dev"
